### ISSUE TITLE
Cannot set properties of null (setting '_setStyle')

### ISSUE THREAD

**Issue by godind** [Robloche/chartjs-plugin-streaming#5]
Hi,

I know you've forked this and probably don't want to fix this but....just in case. Thanks anyway!

Using Chart.js 4.4.2 with a simple line chart and I get this error every time I move between two page (on leaving the chart page and going to another chart page). They both have the same chart.

> Push Model (Listening Based)

```
ERROR TypeError: Cannot set properties of null (setting '_setStyle')
    at /Users/godind/Documents/GitHub/Kip/node_modules/@robloche/chartjs-plugin-streaming/dist/chartjs-plugin-streaming.esm.js:787:27
    at each (/Users/godind/Documents/GitHub/Kip/node_modules/chart.js/dist/chunks/helpers.segment.js:92:20)
    at Chart.update (/Users/godind/Documents/GitHub/Kip/node_modules/@robloche/chartjs-plugin-streaming/dist/chartjs-plugin-streaming.esm.js:785:9)
    at /Users/godind/Documents/GitHub/Kip/node_modules/@robloche/chartjs-plugin-streaming/dist/chartjs-plugin-streaming.esm.js:601:13
    at callback (/Users/godind/Documents/GitHub/Kip/node_modules/chart.js/dist/chunks/helpers.segment.js:79:19)
    at /Users/godind/Documents/GitHub/Kip/node_modules/@robloche/chartjs-plugin-streaming/dist/chartjs-plugin-streaming.esm.js:68:35
    at timer (/Users/godind/Documents/GitHub/Kip/node_modules/zone.js/fesm2015/zone.js:2402:41)
    at _ZoneDelegate.invokeTask (/Users/godind/Documents/GitHub/Kip/node_modules/zone.js/fesm2015/zone.js:403:31)
    at /Users/godind/Documents/GitHub/Kip/node_modules/@angular/core/fesm2022/core.mjs:15287:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (http://192.168.10.43:4200/@mxtommy/kip/main.js:111087:30) {stack: 'TypeError: Cannot set properties of null (set…68.10.43:4200/@mxtommy/kip/main.js:111087:30)', message: 'Cannot set properties of null (setting '_setStyle')'}
```

**Comment by godind** [comment]
Found the problem. Did call chart.destroy() before moving pages. Sorry for the trouble!
